name: Link and Lint PR with Jira Ticket Number
on:
  merge_group:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  get-version:
    runs-on: ubuntu-latest
    # Run only if the PR is not from a Fork / external contributor
    if: ${{ github.repository_owner == 'wireapp' }}
    outputs:
      version_name: ${{ steps.version.outputs.version_name }}
    steps:
      - name: Get version name from source
        id: version
        run: |
          VERSION=do-stuff-to-get-version
          echo "version_name=$VERSION" >> $GITHUB_OUTPUT

  add-jira-description:
    needs: get-version
    uses: wireapp/.github/.github/workflows/jira-link-pr-reusable.yml@{latest-version-commit-hash}
    with:
      skip-branches: '^(production-release|main|master|release\/v\d+)$'
      skip-actors: 'dependabot[bot],AndroidBob'
      version-name: ${{ needs.get-version.outputs.version_name }}
      fix-version-regex: '(?:^|[\s\-_])(v?\d+\.\d+(?:\.\d+)?(?:[\-\+][\w\.\-]*)?)'
      fix-version-wildcards: 'Not applicable'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      jira-token: ${{ secrets.JIRA_TOKEN }}
